name: Build for Windows and macOS M2

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze

      - name: Build Executable
        run: |
          python setup.py build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlappyGame-Windows
          path: build/exe.win-amd64-3.10/

  build-macos-m2:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze

      - name: Build Executable
        run: |
          python setup.py build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlappyGame-MacOS-M2
          path: build/exe.macosx-<arch>-3.10/
